<a href="https://colab.research.google.com/github/ttma333/python/blob/main/pt1_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이토치(PyThorch) 튜토리얼

https://tutorials.pytorch.kr/

# 파이토치(PyTorch)

* 페이스북이 초기 루아(Lua) 언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년도에 공개
* 초기에 토치(Torch)는 넘파이(NumPy) 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
* 이후 GPU를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크로 발전시킴
* 파이썬답게 만들어졌고, 유연하면서도 가속화된 계산 속도를 제공


## 파이토치의 구성요소

- `torch`: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- `torch.autograd`: 자동 미분 기능을 제공하는 라이브러리
- `torch.nn`: 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리
- `torch.optim`: SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx`: ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용


## 텐서(Tensors)

* 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능


In [1]:
import torch
torch.__version__

'1.13.0+cu116'

## 텐서 초기화와 데이터 타입

### 초기화 되지 않은 텐서

In [2]:
x = torch.empty(4,2)
print(x)

tensor([[4.3733e-34, 0.0000e+00],
        [3.5032e-44, 0.0000e+00],
        [       nan, 0.0000e+00],
        [1.1578e+27, 7.1463e+22]])


In [3]:
import numpy as np
x = np.empty([4,2])
print(x)

[[6.68736587e-316 1.77863633e-322]
 [2.12199579e-314 2.23674517e-046]
 [1.10156789e-094 3.51757736e+180]
 [3.90842270e+160 3.43135775e-315]]


### 무작위로 초기화된 텐서


In [6]:
x = torch.rand(4,2) # 0~1 사이의 숫자를 균등하게 생성
print(x)

tensor([[0.9648, 0.8150],
        [0.4553, 0.1485],
        [0.2433, 0.6767],
        [0.5771, 0.5016]])


데이터 타입(dtype)이 long이고 0으로 채워진 텐서


In [14]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)


tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [7]:
x = torch.tensor([3,2,3])
print(x)

tensor([3, 2, 3])


2 x 4크기, double 타입 1로채워진 텐서

In [8]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


x와 같은 크기,float 타입,무작위로 채워진 텐서


In [13]:
x = torch.rand_like(x,dtype=torch.float)  # 사이즈를 튜플로 입력하지 않고 기존의 텐서를 정의
print(x)

tensor([[0.2031, 0.6736, 0.3010, 0.6323],
        [0.2934, 0.2413, 0.9717, 0.4860]])


In [15]:
x = torch.randn(5) # 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성
print(x)

tensor([ 1.5608, -3.5864,  1.6544,  0.1601,  1.2307])


텐서의 크기 계산


In [17]:
print(x.size())

torch.Size([5])


## 데이터 타입(Data Type)

| Data type | dtype | CPU tensor | GPU tensor |
| ------ | ------ | ------ | ------ |
| 32-bit floating point | `torch.float32` or `torch.float` |`torch.FloatTensor` | `torch.cuda.FloatTensor` |
| 64-bit floating point | `torch.float64` or `torch.double` |`torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point | `torch.float16` or `torch.half` |`torch.HalfTensor` | `torch.cuda.HalfTensor` |
| 8-bit integer(unsinged) | `torch.uint8` |`torch.ByteTensor` | `torch.cuda.ByteTensor` |
| 8-bit integer(singed) | `torch.int8` |`torch.CharTensor` | `torch.cuda.CharTensor` |
| 16-bit integer(signed) | `torch.int16` or `torch.short` |`torch.ShortTensor` | `torch.cuda.ShortTensor` |
| 32-bit integer(signed) | `torch.int32` or `torch.int` |`torch.IntTensor` | `torch.cuda.IntTensor` |
| 64-bit integer(signed) | `torch.int64` or `torch.long` |`torch.LongTensor` | `torch.cuda.LongTensor` |


In [20]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [21]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [22]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [23]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


## CUDA Tensors
- .to 메소드를 사용하여 텐서를 어떠한장치(cpu,gpu)로도 옮길 수 있음
- NVIDIA가 만든 병렬 컴퓨팅 플랫폼 및 API 모델로, 보통 '쿠다'라고 발음한다. CUDA 플랫폼은 GPU 의 가상 명령어셋을 사용할 수 있도록 만들어주는 소프트웨어 레이어이며, NVIDIA가 만든 CUDA 코어가 장착된 GPU에서 작동


In [25]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.9044])
-1.9044173955917358
torch.float32


In [1]:
# gpu 연결 끊었을때
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [1]:
# gpu 연결 했을때
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


## 다차원 텐서 표현

### 0D Tensor(Scalar)
- 하나의 숫자를 담고 있는 텐서(tensor)
- 축과 형상이 없음

In [7]:
t0 = torch.tensor(2)

print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(2)


### 1D Tensor(vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [9]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재
- 일반적인 수치,통계 데이터셋이 해당
- 주로 샘플(samples)과 특성(features)을 가진 구조로 사용 

In [11]:
t2= torch.tensor([[1,2,3],[4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 3D Tensor
- 큐브(cube)와 같은 모양으로 세개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간축기 포함된 시계역 데이터에 해당
- 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
- 주로 샘플(samples),타임스텝(timesteps),features 를 가진구조로 이용

## 텐서의 연산(Operations)
- 텐서에 대한 수학연산,삼각함수,비트연산,비교연산,집계 등제공

In [34]:
# https://aigong,tistory,com/1178
import math

a = torch.randn(1,2)
print(a)
print(torch.abs(a)* 2 - 1) # 가우시안 표준정규 분포
print(torch.ceil(a))
print(torch.FloatTensor(a))
print(torch.clamp(a,-0.5,0.5))


tensor([[ 1.1306, -0.6750]])
tensor([[1.2611, 0.3499]])
tensor([[2., -0.]])
tensor([[ 1.1306, -0.6750]])
tensor([[ 0.5000, -0.5000]])


In [24]:
# torch.clamp : 입력값이 min < x(input) < max이면 x가 그대로 나오지만
# min 보다 작으면 min 값이, max 보다 크면 max 값이 나오는 구조
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,1])))


tensor([[-0.7559, -0.8169]])
tensor(-0.8169)
tensor(-0.7559)
tensor(-0.7864)
tensor(0.0431)
tensor(0.6175)
tensor([1, 2, 3])


????
- argmax : 최대값을 가진 인덱스
- argmin : 최소값을 가진 인덱스


In [14]:
x = torch.rand(2,2)
print(x,'\n')
print(x.max(dim=0),'\n')
print(x.max(dim=1))

tensor([[0.3239, 0.8927],
        [0.5777, 0.9100]]) 

torch.return_types.max(
values=tensor([0.5777, 0.9100]),
indices=tensor([1, 1])) 

torch.return_types.max(
values=tensor([0.8927, 0.9100]),
indices=tensor([1, 1]))


In [17]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.7386, 0.0607],
        [0.0457, 0.9530]])
tensor([[0.9986, 0.3693],
        [0.9482, 0.9476]])


torch.add:덧셈

In [19]:
print(x+y)
print(torch.add(x,y))

tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])


결과 텐서를 인자로 제공

In [20]:
result = torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])


<ipython-input-20-fa27375dc8ba>:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:17.)
  torch.add(x,y,out=result)


in-place 방식
- in-place 방식으로 텐서의 값을 변경하는 연산 뒤에는 _가붙음
- x.copy_(y),x.t_()

In [21]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.7386, 0.0607],
        [0.0457, 0.9530]])
tensor([[0.9986, 0.3693],
        [0.9482, 0.9476]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])


torch.sub:뺄셈

In [22]:
print(x)
print(y)
print(x-7,'\n')
x.sub_(y)
print(x)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.7386, 0.0607],
        [0.0457, 0.9530]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[-6.2614, -6.9393],
        [-6.9543, -6.0470]]) 

tensor([[-0.9986, -0.3693],
        [-0.9482, -0.9476]])
tensor([[-2.7358, -0.7992],
        [-1.9421, -2.8483]])
tensor([[-2.7358, -0.7992],
        [-1.9421, -2.8483]])


torch.mul: 곱셈

In [26]:
print(x)
print(y)
print(x*y)
x.mul_(y)
print(x)
print(y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[-0.9986, -0.3693],
        [-0.9482, -0.9476]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[-1.7348, -0.1588],
        [-0.9424, -1.8012]])
tensor([[-1.7348, -0.1588],
        [-0.9424, -1.8012]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[-3.0138, -0.0683],
        [-0.9367, -3.4234]])
tensor([[-3.0138, -0.0683],
        [-0.9367, -3.4234]])


torch.div:나눗셈

In [27]:
print(x)
print(y)
print(x/y)
x.div_(y)
print(x)
print(y)
print(torch.div(x,y))
print(x.div(y))

tensor([[-1.7348, -0.1588],
        [-0.9424, -1.8012]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[-0.9986, -0.3693],
        [-0.9482, -0.9476]])
tensor([[-0.9986, -0.3693],
        [-0.9482, -0.9476]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[-0.5748, -0.8588],
        [-0.9540, -0.4986]])
tensor([[-0.5748, -0.8588],
        [-0.9540, -0.4986]])


torch.mm:내적(dot product)

In [28]:
print(x)
print(y)

print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)
print(torch.svd(z)) # singular value decomposition A= U 시그마 VT

tensor([[-0.9986, -0.3693],
        [-0.9482, -0.9476]])
tensor([[1.7372, 0.4300],
        [0.9939, 1.9007]])
tensor([[-2.1018, -1.1312],
        [-2.5891, -2.2089]])
tensor([[-2.1018, -1.1312],
        [-2.5891, -2.2089]])
torch.return_types.svd(
U=tensor([[-0.5712, -0.8208],
        [-0.8208,  0.5712]]),
S=tensor([4.1362, 0.4144]),
V=tensor([[ 0.8041,  0.5946],
        [ 0.5946, -0.8041]]))


##텐서의 조작(Manupulations)

인덱싱(indexing):Numpy 처럼 인덱싱 형태로 사용가능

In [30]:
import torch
x = torch.Tensor([[1,2],[3,4]])
print(x)

print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])
print(x[:,0])
print(x[:,1])
print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


https://bigdatadiary0819.tistory.com/60

º 랜덤한 값을 가지는 텐서 생성

1. torch.rand() : 0과 1 사이의 숫자를 균등하게 생성

2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성

4. torch.randn_like() :  사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32

6. torch.randint_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성


º 특정한 값을 가지는 텐서 생성

1. torch.arange() : 주어진 범위 내의 정수를 순서대로 생성

2. torch.ones() : 주어진 사이즈의 1로 이루어진 텐서 생성

3. torch.zeros() : 주어진 사이즈의 0으로 이루어진 텐서 생성

4. torch.ones_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.zeros_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

6. torch.linspace() : 시작점과 끝점을 주어진 갯수만큼 균등하게 나눈 간격점을 행벡터로 출력
7. torch.logspace() : 시작점과 끝점을 주어진 갯수만큼 로그간격으로 나눈 간격점을 행벡터로 출력


view: 텐서의 크기(size)나 모양(shape)을 변경
- 기본적으로 변경 전과 후에 텐서 안의 원소 개수가 유지되어야 함
- -1로 설정되면 계산을 통해 해당 크기값을 유추

In [32]:
import torch
x= torch.randn(4,5)
print(x)
print(x.shape)
print(x.size())

tensor([[ 0.1674,  0.9354, -0.6482, -0.6984, -0.2293],
        [-0.3815,  0.6416, -1.3891, -0.0877,  0.4265],
        [ 0.9279,  0.4010, -1.1499, -1.3837, -0.3819],
        [ 2.2478,  1.0086, -1.3202, -0.7987, -1.7951]])
torch.Size([4, 5])
torch.Size([4, 5])


In [33]:
x = torch.FloatTensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

#size를 활용한 텐서사이즈 보기
print(x.size())
#shape를 활용한 텐서사이즈 보기
print(x.shape)
#dim을 활용한 텐서사이즈 보기
print(x.dim())
#0차원 사이즈 확인
print(x.size(0))
#1차원 사이즈 확인
print(x.shape[0])

torch.Size([4, 2])
torch.Size([4, 2])
2
4
4


In [36]:
x = torch.randn(4,5)
print(x)
print()
y = x.view(20)
print(y)
z = x.view(5,-1)
print()
print(z)

tensor([[ 1.4698,  0.3338, -0.1622, -2.1548, -0.8369],
        [ 0.2351,  0.0415,  1.4121, -1.6841, -0.3629],
        [-0.1062,  1.0826, -2.2371, -0.6499, -1.4762],
        [ 1.2188,  1.2010, -0.0166, -0.0720,  0.3997]])

tensor([ 1.4698,  0.3338, -0.1622, -2.1548, -0.8369,  0.2351,  0.0415,  1.4121,
        -1.6841, -0.3629, -0.1062,  1.0826, -2.2371, -0.6499, -1.4762,  1.2188,
         1.2010, -0.0166, -0.0720,  0.3997])

tensor([[ 1.4698,  0.3338, -0.1622, -2.1548],
        [-0.8369,  0.2351,  0.0415,  1.4121],
        [-1.6841, -0.3629, -0.1062,  1.0826],
        [-2.2371, -0.6499, -1.4762,  1.2188],
        [ 1.2010, -0.0166, -0.0720,  0.3997]])


item: 텐서에 값이 단하나라도 존재하면 숫자값을 얻을 수 있음

In [37]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.2262])
-0.22615854442119598
torch.float32


squeeze: 차원을 축소(제거)


In [38]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.5375, 0.8411, 0.2225],
         [0.8385, 0.5607, 0.6371],
         [0.2522, 0.8576, 0.6970]]])
torch.Size([1, 3, 3])


unsqueeze : 차원을 증가(생성)

In [43]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.4129, 0.5453, 0.1062],
        [0.5986, 0.4486, 0.4866],
        [0.7872, 0.4304, 0.9477]])
torch.Size([3, 3])


In [44]:
tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.4129, 0.5453, 0.1062],
         [0.5986, 0.4486, 0.4866],
         [0.7872, 0.4304, 0.9477]]])
torch.Size([1, 3, 3])


In [45]:
tensor = tensor.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[[0.4129, 0.5453, 0.1062]],

         [[0.5986, 0.4486, 0.4866]],

         [[0.7872, 0.4304, 0.9477]]]])
torch.Size([1, 3, 1, 3])


stack : 텐서가 결합

In [46]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)
print(torch.stack([x,y,z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


###cat:텐서를 결합하는 메소드(concatenate)
- 넘파이의 stack과 유사하지만,쌓을 dim이 존재해야함
- 해당 차원을늘려준후 결합

In [48]:
a= torch.randn(1,3,3)
print(a)
b=torch.randn(1,3,3)
print(b)
c=torch.cat((a,b),dim=0)
print(c)
print(c.size())

tensor([[[-0.0153, -1.6214,  0.5192],
         [ 0.6709, -0.9393, -0.4084],
         [ 0.9390, -1.0101,  0.3590]]])
tensor([[[ 0.0253, -0.0498, -1.4728],
         [ 1.6753, -1.2639, -1.5909],
         [-0.2705,  2.2813, -0.5680]]])
tensor([[[-0.0153, -1.6214,  0.5192],
         [ 0.6709, -0.9393, -0.4084],
         [ 0.9390, -1.0101,  0.3590]],

        [[ 0.0253, -0.0498, -1.4728],
         [ 1.6753, -1.2639, -1.5909],
         [-0.2705,  2.2813, -0.5680]]])
torch.Size([2, 3, 3])


In [49]:
c = torch.cat((a,b),dim=1)
print(c)
print(c.size())

tensor([[[-0.0153, -1.6214,  0.5192],
         [ 0.6709, -0.9393, -0.4084],
         [ 0.9390, -1.0101,  0.3590],
         [ 0.0253, -0.0498, -1.4728],
         [ 1.6753, -1.2639, -1.5909],
         [-0.2705,  2.2813, -0.5680]]])
torch.Size([1, 6, 3])
